apiVersion: apps/v1
kind: Deployment
metadata:
  name: sale
  labels:
    app: sale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sale
  template:
    metadata:
      labels:
        app: sale
    spec:
      containers:
        - name: sale
          image: jinunkim/homesale:0403
          ports:
            - containerPort: 8080
